INSERT INTO `tb_genre`(`id`, `name`) VALUES ('1', 'Action'),
                                            ('11', 'Strategy'),
                                            ('21', 'Sports'),
                                            ('31', 'Adventure'),
                                            ('41', 'Role-Playing'),
                                            ('51', 'Driving/Racing'),
                                            ('61', 'Simulation'),
                                            ('71', 'Educational'),
                                            ('81', 'Fighting'),
                                            ('91', 'Wrestling'),
                                            ('101', 'Shooter'),
                                            ('111', 'Real-Time Strategy'),
                                            ('121', 'Card Game'),
                                            ('131', 'Trivia/Board Game'),
                                            ('141', 'Compilation'),
                                            ('151', 'MMORPG'),
                                            ('161', 'Minigame Collection'),
                                            ('171', 'Puzzle'),
                                            ('181', 'Music/Rhythm'),
                                            ('191', 'Boxing'),
                                            ('201', 'Football'),
                                            ('211', 'Basketball'),
                                            ('221', 'Skateboarding'),
                                            ('231', 'Flight Simulator'),
                                            ('241', 'Tennis'),
                                            ('251', 'Billiards'),
                                            ('261', 'Fishing'),
                                            ('271', 'Golf'),
                                            ('281', 'Bowling'),
                                            ('291', 'Pinball'),
                                            ('301', 'Dual-Joystick Shooter'),
                                            ('311', 'First-Person Shooter'),
                                            ('321', 'Snowboarding/Skiing'),
                                            ('331', 'Baseball'),
                                            ('341', 'Light-Gun Shooter'),
                                            ('351', 'Text Adventure'),
                                            ('361', 'Brawler'),
                                            ('371', 'Vehicular Combat'),
                                            ('381', 'Hockey'),
                                            ('391', 'Soccer'),
                                            ('401', 'Platformer'),
                                            ('411', 'Track & Field'),
                                            ('421', 'Action-Adventure'),
                                            ('431', 'Fitness'),
                                            ('441', 'Block-Breaking'),
                                            ('451', 'Cricket'),
                                            ('461', 'Surfing'),
                                            ('471', 'Shoot Em Up'),
                                            ('481', 'Gambling'),
                                            ('491', 'MOBA');